print("+-----------------------------------------------------+")
print("|                                       April-8       |")
print("|                                 Boduppal,Hyd        |")
print("| Dear Self,                                          |")
print("|                                                     |")
print("|              Feeling good restarting programming    |")
print("|           Always remember you want to become a      |")
print("|                Robotic Scientist At Google          |")
print("| To myself from the future never lose hope if nobody |")
print("| if nobody stays with you that's great be            |")
print("|  Alone that's damn powerful to succeed you must     |")
print("|      be alone you can do it Achieve evrything alone |")
print("|                                                     |")
print("|                                    Akshay😎        |")
print("|                                                     |")
print("+-----------------------------------------------------+")
